### ISSUE TITLE
one gene showed up multiple times in result

### ISSUE THREAD

**Issue by mick42-star** [RJWANGbioinfo/APAlyzer#12]
my input bam file is pair-end sorted bam, and scripts are as below

GTFfile="Mus_musculus.GRCm39.104.gtf"
PASREFraw=PAS2GEF(GTFfile)	
refUTRraw=PASREFraw$refUTRraw
dfIPAraw=PASREFraw$dfIPA
dfLEraw=PASREFraw$dfLE
PASREF=REF4PAS(refUTRraw,dfIPAraw,dfLEraw)
UTRdbraw=REF3UTR(refUTRraw)

DFUTRraw=PASEXP_3UTR(UTRdbraw, flsall, Strandtype="forward")

The result overall seems ok, but one gene Ptp4a1 popped up 4080 times. I am so confused. Could you please give some suggestions?
<img width="272" alt="Screenshot 2022-02-15 181210" src="https://user-images.githubusercontent.com/45997340/154019992-6ef6ecd1-69e5-48bd-8b64-fc2a10d875e0.png">

**Comment by Riverhuang42** [comment]
<img width="272" alt="image" src="https://user-images.githubusercontent.com/45997340/154019778-7da586dd-53fd-44e3-8019-4d508b2b1ad4.png">

**Comment by PieraccioliM** [comment]
Hi, you should check if ptp4a1 appears two or more times in your annotation. I had the same issue when I accidentally duplicated the apa annotation for a gene.

**Comment by mick42-star** [comment]
> Hi, you should check if ptp4a1 appears two or more times in your annotation. I had the same issue when I accidentally duplicated the apa annotation for a gene.

Hi, thanks for your help. The annotation should be OK since the other downstream analysis is all done with no problems.

**Comment by RJWANGbioinfo** [comment]
@Riverhuang42 thanks for the feedback, the issue is specifically caused by the format changes in ensembl's GRCm39 gtf compared to the previous GRCm38 version. I have updated APALyzer to ver 1.9.3, this issue should be fixed now. please update your APAlyzer through `BiocManager::install('RJWANGbioinfo/APAlyzer')`, then 

```
library(GenomicRanges)
library(APAlyzer)
GTFfile="Mus_musculus.GRCm39.105.gtf.gz"
PASREFraw=PAS2GEF(GTFfile)
```

**Comment by RJWANGbioinfo** [comment]
close the ticket, since it is fixed

**Comment by mick42-star** [comment]
Hi, I updated APALyzer to ver 1.9.4. The problem seems unsolved. I still have the same problem.

**Comment by RJWANGbioinfo** [comment]
@Riverhuang42 , for us to repeat this issue from our end, do you mind sharing a subset of your bam file that has this issue?

**Comment by mick42-star** [comment]
[https://outlook-1.cdn.office.net/assets/mail/file-icon/png/generic_16x16.png]Y2-sort_chr.bam<https://1drv.ms/u/s!Av48IoLnk1dQghRnKnkZkU81PfMz>
[https://outlook-1.cdn.office.net/assets/mail/file-icon/png/generic_16x16.png]A90-sort_chr.bam<https://1drv.ms/u/s!Av48IoLnk1dQghXMQx6JRxlPsxlN>
Hi Ruijia, Many thanks for your help. I am not sure how to share bam file in GitHub, so I attached to this email here.

________________________________

**Comment by RJWANGbioinfo** [comment]
@Riverhuang42 sorry for the late reply, I'm just back from vacation, I seems can not download your outlook links. If you subsetted bam file < 10 MB you can share it through the instruction of Github:
https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/attaching-files

If your file is >10 MB, you may want to consider to share them through google drive or dropbox, thanks

**Comment by mick42-star** [comment]
> @Riverhuang42 sorry for the late reply, I'm just back from vacation, I seems can not download your outlook links. If you subsetted bam file < 10 MB you can share it through the instruction of Github: https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/attaching-files
> 
> If your file is >10 MB, you may want to consider to share them through google drive or dropbox, thanks

Hi Many thanks to your reply. I share the file in the google drive.
https://drive.google.com/drive/folders/1fFx5UEVBIOPIuR-tLSqqLPpI8Y-boYyx?usp=sharing

**Comment by mick42-star** [comment]
Hi Many thanks to your reply. I share the file in the google drive.
https://drive.google.com/drive/folders/1fFx5UEVBIOPIuR-tLSqqLPpI8Y-boYyx?usp=sharing

**Comment by RJWANGbioinfo** [comment]
@mick42-star , sorry for the late reply, we just tested it using the bams from you, we can not repeat your issue from our end.  Below is the test log:

```
library(APAlyzer)
### load reference ### 
GTFfile="Mus_musculus.GRCm39.105.gtf.gz"
PASREFraw=PAS2GEF(GTFfile)
refUTRraw=PASREFraw$refUTRraw
dfIPAraw=PASREFraw$dfIPA
dfLEraw=PASREFraw$dfLE
PASREF=REF4PAS(refUTRraw,dfIPAraw,dfLEraw)

### confirm Ptp4a1 in reference ### 
refUTRraw[refUTRraw$gene_symbol=="Ptp4a1",]

### Load bam files ###
flsall <- dir(getwd(),".bam")
flsall<-paste0(getwd(),'/',flsall)
names(flsall)<-gsub('.bam','',dir(getwd(),".bam"))

### count 3UTR PAS ###
DFUTRraw=PASEXP_3UTR(UTRdbraw, flsall)
head(DFUTRraw) 

### check Ptp4a1 ###
DFUTRraw[DFUTRraw$gene_symbol=="Ptp4a1",]
``` 

And here is the screenshot of the results:
1. confirm Ptp4a1 in reference:
![image](https://user-images.githubusercontent.com/51307984/177210215-48d00fa2-68f2-4237-86df-068d17ce9c3c.png)

2. confirm the quantification looks fine in the whole result:
![image](https://user-images.githubusercontent.com/51307984/177210263-f526b028-a50c-4dde-aaca-e80b02261439.png)

3. No issue is observed in `Ptp4a1`
![image](https://user-images.githubusercontent.com/51307984/177210353-cbdbb014-a0cf-4901-82c2-d22f21064c47.png)

4. confirm we are using the same bam files
![image](https://user-images.githubusercontent.com/51307984/177210449-dec08409-3701-4028-bfd0-db5083271561.png)


Based on what we've observed from our side, we have reason to believe the issues are caused by your annotation file (GTF).

If you want to repeat the above process, please make sure:
- you are using the latest version of APAlyzer
- you are using the same or latest GTF file from ensemble ("Mus_musculus.GRCm39.105.gtf.gz")

**Comment by RJWANGbioinfo** [comment]
close this ticket due to:
1. we can not the repeat the issue
2. the issues seems relevant to GTF file used by the user other than the code of APAlyzer
